/**
 * State machine de transiciones permitidas
 * Cada estado mapea a los estados a los que PUEDE transicionar
 */
export const TRANSICIONES_PERMITIDAS: Record<string, string[]> = {
  BORRADOR: ['PENDIENTE_PAGO', 'ANULADO'],
  PENDIENTE_PAGO: ['PAGO_CONFIRMADO', 'ANULADO'],
  PAGO_CONFIRMADO: ['EN_VERIFICACION', 'ANULADO'],
  EN_VERIFICACION: ['OBSERVADO', 'APROBADO'],
  OBSERVADO: ['EN_VERIFICACION', 'ANULADO'],
  APROBADO: ['INSPECCION', 'ANULADO'],
  INSPECCION: ['CERTIFICADO_EMITIDO', 'ANULADO'],
  CERTIFICADO_EMITIDO: ['ANULADO'],
  ANULADO: [],
};

/**
 * Roles que pueden hacer cada transición
 */
export const ROLES_TRANSICION: Record<string, string[]> = {
  'BORRADOR:PENDIENTE_PAGO': ['EXTERNO', 'ADMIN'],
  'BORRADOR:ANULADO': ['EXTERNO', 'ADMIN'],
  'PENDIENTE_PAGO:PAGO_CONFIRMADO': ['SISTEMA'],
  'PENDIENTE_PAGO:ANULADO': ['EXTERNO', 'ADMIN'],
  'PAGO_CONFIRMADO:EN_VERIFICACION': ['ADMIN', 'INSPECTOR'],
  'EN_VERIFICACION:OBSERVADO': ['INSPECTOR', 'ADMIN'],
  'EN_VERIFICACION:APROBADO': ['INSPECTOR', 'ADMIN'],
  'OBSERVADO:EN_VERIFICACION': ['EXTERNO', 'ADMIN'],
  'OBSERVADO:ANULADO': ['ADMIN'],
  'APROBADO:INSPECCION': ['ADMIN', 'INSPECTOR'],
  'INSPECCION:CERTIFICADO_EMITIDO': ['ADMIN'],
  '*:ANULADO': ['ADMIN'],
};