/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "bomberos-red": "#C8102E",
        "bomberos-gold": "#F2A900",
        "bomberos-navy": "#1E293B",
        "bomberos-dark": "#0F172A",
        "bomberos-light": "#F8FAFC",
        "primary": "#b70011",
        "primary-container": "#dc2626",
        "on-primary": "#ffffff",
        "on-primary-container": "#fff6f5",
        "secondary": "#545f73",
        "secondary-container": "#d5e0f8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#586377",
        "tertiary": "#004ed0",
        "tertiary-container": "#2d68f0",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f8f7ff",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#5c403c",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "outline": "#916f6b",
        "outline-variant": "#e6bdb8",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "title-sm": ["Inter"],
        "title-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "label-lg": ["Inter"],
        "display-lg": ["Inter"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
      },
      spacing: {
        "gutter": "1.5rem",
        "gutter-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
